// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5zx-ah-bKUQpwD2vl2gvJCi3UrvhPUB4',
    appId: '1:88721675181:web:57f94cdda0a9d36f710724',
    messagingSenderId: '88721675181',
    projectId: 'csi-app-2024',
    authDomain: 'csi-app-2024.firebaseapp.com',
    databaseURL: 'https://csi-app-2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csi-app-2024.appspot.com',
    measurementId: 'G-9LMC9Q5Z86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTqCSdTpBTjQrs2Wxhd4RlqCGMwsaY7H0',
    appId: '1:88721675181:android:366f79865c2aac9e710724',
    messagingSenderId: '88721675181',
    projectId: 'csi-app-2024',
    databaseURL: 'https://csi-app-2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csi-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4RPJVUi57OVPVKHMg-sPtYa4leiFXUYs',
    appId: '1:88721675181:ios:8e420f9c5be9793b710724',
    messagingSenderId: '88721675181',
    projectId: 'csi-app-2024',
    databaseURL: 'https://csi-app-2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csi-app-2024.appspot.com',
    iosClientId: '88721675181-vub3eafn8ul6f31qrno7i1mslcqn1omi.apps.googleusercontent.com',
    iosBundleId: 'com.example.csiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4RPJVUi57OVPVKHMg-sPtYa4leiFXUYs',
    appId: '1:88721675181:ios:04d7b1156e5fec5c710724',
    messagingSenderId: '88721675181',
    projectId: 'csi-app-2024',
    databaseURL: 'https://csi-app-2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'csi-app-2024.appspot.com',
    iosClientId: '88721675181-7uc7bo0vag6ukc58qi4foh1e183u1g48.apps.googleusercontent.com',
    iosBundleId: 'com.example.csiApp.RunnerTests',
  );
}
